using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MergePatchDto.Generators
{
    internal static class SourceTextEmitter
    {
        private static readonly SymbolDisplayFormat FullyQualifiedNullableFormat = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        private static readonly SymbolDisplayFormat FullyQualifiedTypeOfFormat = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

        public static string Emit(PatchDtoModel model, Compilation compilation, SourceProductionContext context)
        {
            if (model.Targets.Length > 0)
            {
                ReportPropertyAttributeConflicts(model, context);
            }
            else
            {
                ReportTargetlessMappingAttributes(model, context);
            }

            var builder = new StringBuilder();
            var generatedNames = GeneratedNames.Create(model);
            var converterTypeName = GetGlobalTypeName(model.NamespaceName, generatedNames.ConverterTypeName);
            var indent = string.IsNullOrEmpty(model.NamespaceName) ? string.Empty : "    ";

            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            if (!string.IsNullOrEmpty(model.NamespaceName))
            {
                builder.Append("namespace ").Append(model.NamespaceName).AppendLine();
                builder.AppendLine("{");
            }

            builder.Append(indent)
                .Append("[global::System.Text.Json.Serialization.JsonConverter(typeof(")
                .Append(converterTypeName)
                .AppendLine("))]");
            builder.Append(indent)
                .Append(model.Accessibility)
                .Append(" partial class ")
                .Append(model.Name)
                .AppendLine();
            builder.Append(indent).AppendLine("{");

            AppendPresenceApi(builder, model, generatedNames, indent + "    ");

            foreach (var target in model.Targets)
            {
                AppendApplyTo(builder, model, target, compilation, context, indent + "    ");
            }

            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            AppendConverter(builder, model, generatedNames, indent);

            if (!string.IsNullOrEmpty(model.NamespaceName))
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        public static string GetHintName(PatchDtoModel model)
        {
            var name = model.TypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var builder = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    builder.Append(c);
                }
                else
                {
                    builder.Append('_');
                }
            }

            return builder + ".MergePatch.g.cs";
        }

        private static void AppendPresenceApi(StringBuilder builder, PatchDtoModel model, GeneratedNames generatedNames, string indent)
        {
            builder.Append(indent).Append("private readonly global::System.Collections.Generic.HashSet<string> ")
                .Append(generatedNames.ProvidedFieldName)
                .AppendLine(" = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);");
            builder.AppendLine();
            builder.Append(indent).AppendLine("public ProvidedFields Has");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    get { return new ProvidedFields(this); }");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).Append("internal bool ").Append(generatedNames.WasProvidedMethodName).AppendLine("(string propertyName)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (propertyName == null)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        throw new global::System.ArgumentNullException(nameof(propertyName));");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).Append("    return ").Append(generatedNames.ProvidedFieldName).AppendLine(".Contains(propertyName);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).Append("internal void ").Append(generatedNames.MarkProvidedMethodName).AppendLine("(string propertyName)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    ").Append(generatedNames.ProvidedFieldName).AppendLine(".Add(propertyName);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).Append("internal void ").Append(generatedNames.ClearProvidedMethodName).AppendLine("()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    ").Append(generatedNames.ProvidedFieldName).AppendLine(".Clear();");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).AppendLine("public readonly struct ProvidedFields");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    private readonly ").Append(model.TypeName).AppendLine(" _patch;");
            builder.AppendLine();
            builder.Append(indent).Append("    public ProvidedFields(").Append(model.TypeName).AppendLine(" patch)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        _patch = patch;");
            builder.Append(indent).AppendLine("    }");

            foreach (var property in model.Properties)
            {
                builder.AppendLine();
                builder.Append(indent)
                    .Append("    public bool ")
                    .Append(EscapeIdentifier(property.Name))
                    .Append(" { get { return _patch.")
                    .Append(generatedNames.WasProvidedMethodName)
                    .Append("(")
                    .Append(ToLiteral(property.Name))
                    .AppendLine("); } }");
            }

            builder.Append(indent).AppendLine("}");
        }

        private static void AppendApplyTo(
            StringBuilder builder,
            PatchDtoModel model,
            PatchTargetModel target,
            Compilation compilation,
            SourceProductionContext context,
            string indent)
        {
            var targetTypeName = ToTypeName(target.TargetType);

            builder.AppendLine();
            builder.Append(indent).Append("public void ApplyTo(").Append(targetTypeName).AppendLine(" target)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (target == null)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        throw new global::System.ArgumentNullException(nameof(target));");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    var has = Has;");

            foreach (var property in model.Properties)
            {
                if (HasConflictingApplyAttributes(property))
                {
                    continue;
                }

                if (property.HasPatchIgnore)
                {
                    continue;
                }

                if (property.PatchUsingMethodName != null)
                {
                    AppendPatchUsing(builder, model, target, property, context, indent + "    ");
                    continue;
                }

                AppendDirectAssignment(builder, model, target, property, compilation, context, indent + "    ");
            }

            builder.Append(indent).AppendLine("}");
        }

        private static void AppendDirectAssignment(
            StringBuilder builder,
            PatchDtoModel model,
            PatchTargetModel target,
            PatchPropertyModel property,
            Compilation compilation,
            SourceProductionContext context,
            string indent)
        {
            var targetPropertyName = property.PatchToTargetName ?? property.Name;
            var targetProperty = target.TargetType
                .GetMembers(targetPropertyName)
                .OfType<IPropertySymbol>()
                .FirstOrDefault(member => !member.IsStatic);

            if (targetProperty == null)
            {
                var descriptor = property.PatchToTargetName == null
                    ? Diagnostics.ConventionTargetMissing
                    : Diagnostics.PatchToTargetMissing;

                if (property.PatchToTargetName == null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        descriptor,
                        property.Location,
                        property.Name,
                        ToTypeName(target.TargetType)));
                }
                else
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        descriptor,
                        property.Location,
                        property.Name,
                        targetPropertyName,
                        ToTypeName(target.TargetType)));
                }

                return;
            }

            if (!HasAccessibleSetter(compilation, model.TypeSymbol, target.TargetType, targetProperty))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.TargetPropertyNoSetter,
                    property.Location,
                    targetPropertyName,
                    ToTypeName(target.TargetType),
                    property.Name));
                return;
            }

            if (!CanAssign(compilation, property.Symbol.Type, targetProperty.Type))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.PatchPropertyCannotAssignToTargetProperty,
                    property.Location,
                    property.Name,
                    ToTypeName(property.Symbol.Type),
                    targetPropertyName,
                    ToTypeName(targetProperty.Type),
                    ToTypeName(target.TargetType)));
                return;
            }

            builder.AppendLine();
            builder.Append(indent).Append("if (has.").Append(EscapeIdentifier(property.Name)).AppendLine(")");
            builder.Append(indent)
                .Append("    target.")
                .Append(EscapeIdentifier(targetPropertyName))
                .Append(" = ")
                .Append(EscapeIdentifier(property.Name))
                .AppendLine(";");
        }

        private static void AppendPatchUsing(
            StringBuilder builder,
            PatchDtoModel model,
            PatchTargetModel target,
            PatchPropertyModel property,
            SourceProductionContext context,
            string indent)
        {
            var methodName = property.PatchUsingMethodName!;
            var methods = model.TypeSymbol
                .GetMembers(methodName)
                .OfType<IMethodSymbol>()
                .Where(method => method.MethodKind == MethodKind.Ordinary)
                .ToArray();

            if (methods.Length == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.PatchUsingMethodMissing,
                    property.Location,
                    methodName,
                    property.Name));
                return;
            }

            var method = methods.FirstOrDefault(candidate => IsValidPatchUsingMethod(candidate, model, target, property));
            if (method == null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.PatchUsingMethodInvalid,
                    property.Location,
                    methodName,
                    property.Name,
                    ToTypeName(target.TargetType),
                    property.TypeName,
                    model.TypeName));
                return;
            }

            builder.AppendLine();
            builder.Append(indent).Append("if (has.").Append(EscapeIdentifier(property.Name)).AppendLine(")");
            builder.Append(indent).Append("    ").Append(EscapeIdentifier(methodName)).Append("(");
            if (method.Parameters.Length == 3)
            {
                builder.Append("this, ");
            }

            builder.Append("target, ").Append(EscapeIdentifier(property.Name)).AppendLine(");");
        }

        private static void AppendConverter(StringBuilder builder, PatchDtoModel model, GeneratedNames generatedNames, string indent)
        {
            builder.Append(indent)
                .Append("internal sealed class ")
                .Append(generatedNames.ConverterTypeName)
                .Append(" : global::System.Text.Json.Serialization.JsonConverter<")
                .Append(model.TypeName)
                .AppendLine(">");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent)
                .Append("    public ")
                .Append(generatedNames.ConverterTypeName)
                .AppendLine("()");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();

            AppendConverterRead(builder, model, generatedNames, indent + "    ");
            builder.AppendLine();
            AppendConverterWrite(builder, model, generatedNames, indent + "    ");
            AppendConverterHelpers(builder, model, generatedNames, indent + "    ");

            builder.Append(indent).AppendLine("}");
        }

        private static void AppendConverterRead(StringBuilder builder, PatchDtoModel model, GeneratedNames generatedNames, string indent)
        {
            builder.Append(indent)
                .Append("public override ")
                .Append(model.TypeName)
                .AppendLine("? Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        return null;");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        throw new global::System.Text.Json.JsonException(\"Patch DTO JSON payload must be an object.\");");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent)
                .Append("    ")
                .Append(generatedNames.ValidateJsonNamesMethodName)
                .AppendLine("(options);");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    using (var document = global::System.Text.Json.JsonDocument.ParseValue(ref reader))");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).Append("        var patch = new ").Append(model.TypeName).AppendLine("();");
            builder.AppendLine();
            builder.Append(indent).AppendLine("        foreach (var jsonProperty in document.RootElement.EnumerateObject())");
            builder.Append(indent).AppendLine("        {");
            builder.Append(indent).AppendLine("            var jsonPropertyName = jsonProperty.Name;");

            foreach (var property in model.Properties)
            {
                builder.AppendLine();
                builder.Append(indent).Append("            if (")
                    .Append(generatedNames.JsonNameEqualsMethodName)
                    .Append("(jsonPropertyName, ")
                    .Append(generatedNames.GetJsonNameMethodName)
                    .Append("(")
                    .Append(ToLiteral(property.Name))
                    .Append(", ")
                    .Append(property.ExplicitJsonName == null ? "null" : ToLiteral(property.ExplicitJsonName))
                    .AppendLine(", options), options))");
                builder.Append(indent).AppendLine("            {");

                var deserializeExpression = "global::System.Text.Json.JsonSerializer.Deserialize<" + property.TypeName + ">(jsonProperty.Value, " + GetJsonOptionsExpression(property, "options", generatedNames) + ")";
                if (property.IsInitOnly)
                {
                    builder.Append(indent)
                        .Append("                ")
                        .Append(generatedNames.GetInitOnlySetterMethodName(property))
                        .Append("(patch, ")
                        .Append(deserializeExpression)
                        .AppendLine(");");
                }
                else
                {
                    builder.Append(indent)
                        .Append("                patch.")
                        .Append(EscapeIdentifier(property.Name))
                        .Append(" = ")
                        .Append(deserializeExpression)
                        .AppendLine(";");
                }

                builder.Append(indent)
                    .Append("                patch.")
                    .Append(generatedNames.MarkProvidedMethodName)
                    .Append("(")
                    .Append(ToLiteral(property.Name))
                    .AppendLine(");");
                builder.Append(indent).AppendLine("                continue;");
                builder.Append(indent).AppendLine("            }");
            }

            if (model.RejectUnknownProperties)
            {
                builder.AppendLine();
                builder.Append(indent).AppendLine("            throw new global::System.Text.Json.JsonException(\"Unknown JSON property '\" + jsonPropertyName + \"'.\");");
            }

            builder.Append(indent).AppendLine("        }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("        return patch;");
            builder.Append(indent).AppendLine("    }");
            builder.Append(indent).AppendLine("}");
        }

        private static void AppendConverterWrite(StringBuilder builder, PatchDtoModel model, GeneratedNames generatedNames, string indent)
        {
            builder.Append(indent)
                .Append("public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ")
                .Append(model.TypeName)
                .AppendLine(" value, global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent)
                .Append("    ")
                .Append(generatedNames.ValidateJsonNamesMethodName)
                .AppendLine("(options);");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    writer.WriteStartObject();");

            foreach (var property in model.Properties)
            {
                builder.AppendLine();
                builder.Append(indent)
                    .Append("    if (value.")
                    .Append(generatedNames.WasProvidedMethodName)
                    .Append("(")
                    .Append(ToLiteral(property.Name))
                    .AppendLine("))");
                builder.Append(indent).AppendLine("    {");
                builder.Append(indent)
                    .Append("        writer.WritePropertyName(")
                    .Append(generatedNames.GetJsonNameMethodName)
                    .Append("(")
                    .Append(ToLiteral(property.Name))
                    .Append(", ")
                    .Append(property.ExplicitJsonName == null ? "null" : ToLiteral(property.ExplicitJsonName))
                    .AppendLine(", options));");
                builder.Append(indent)
                    .Append("        global::System.Text.Json.JsonSerializer.Serialize<")
                    .Append(property.TypeName)
                    .Append(">(writer, value.")
                    .Append(EscapeIdentifier(property.Name))
                    .Append(", ")
                    .Append(GetJsonOptionsExpression(property, "options", generatedNames))
                    .AppendLine(");");
                builder.Append(indent).AppendLine("    }");
            }

            builder.AppendLine();
            builder.Append(indent).AppendLine("    writer.WriteEndObject();");
            builder.Append(indent).AppendLine("}");
        }

        private static void AppendConverterHelpers(StringBuilder builder, PatchDtoModel model, GeneratedNames generatedNames, string indent)
        {
            foreach (var property in model.Properties.Where(property => property.IsInitOnly))
            {
                builder.AppendLine();
                builder.Append(indent)
                    .Append("private static void ")
                    .Append(generatedNames.GetInitOnlySetterMethodName(property))
                    .Append("(")
                    .Append(model.TypeName)
                    .Append(" patch, ")
                    .Append(property.TypeName)
                    .AppendLine(" value)");
                builder.Append(indent).AppendLine("{");
                builder.Append(indent)
                    .Append("    var property = typeof(")
                    .Append(model.TypeName)
                    .Append(").GetProperty(")
                    .Append(ToLiteral(property.Name))
                    .AppendLine(", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public);");
                builder.Append(indent).AppendLine("    if (property == null)");
                builder.Append(indent).AppendLine("    {");
                builder.Append(indent).AppendLine("        throw new global::System.InvalidOperationException(\"Patch DTO property could not be found.\");");
                builder.Append(indent).AppendLine("    }");
                builder.AppendLine();
                builder.Append(indent).AppendLine("    property.SetValue(patch, value, null);");
                builder.Append(indent).AppendLine("}");
            }

            foreach (var property in model.Properties.Where(property => property.HasPropertyJsonOptions))
            {
                builder.AppendLine();
                builder.Append(indent)
                    .Append("private static global::System.Text.Json.JsonSerializerOptions ")
                    .Append(generatedNames.GetJsonOptionsMethodName(property))
                    .AppendLine("(global::System.Text.Json.JsonSerializerOptions options)");
                builder.Append(indent).AppendLine("{");
                builder.Append(indent).AppendLine("    var mergePatchOptions = new global::System.Text.Json.JsonSerializerOptions(options);");

                if (property.HasJsonConverterAttribute)
                {
                    builder.Append(indent)
                        .Append("    var property = typeof(")
                        .Append(model.TypeName)
                        .Append(").GetProperty(")
                        .Append(ToLiteral(property.Name))
                        .AppendLine(", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public);");
                    builder.Append(indent).AppendLine("    if (property == null)");
                    builder.Append(indent).AppendLine("    {");
                    builder.Append(indent).AppendLine("        throw new global::System.InvalidOperationException(\"Patch DTO property could not be found.\");");
                    builder.Append(indent).AppendLine("    }");
                    builder.AppendLine();
                    builder.Append(indent).AppendLine("    var converterAttribute = (global::System.Text.Json.Serialization.JsonConverterAttribute?)global::System.Attribute.GetCustomAttribute(property, typeof(global::System.Text.Json.Serialization.JsonConverterAttribute));");
                    builder.Append(indent).AppendLine("    if (converterAttribute == null)");
                    builder.Append(indent).AppendLine("    {");
                    builder.Append(indent).AppendLine("        throw new global::System.InvalidOperationException(\"Patch DTO property converter attribute could not be found.\");");
                    builder.Append(indent).AppendLine("    }");
                    builder.AppendLine();
                    builder.Append(indent).AppendLine("    global::System.Text.Json.Serialization.JsonConverter? converter;");
                    builder.Append(indent).AppendLine("    if (converterAttribute.ConverterType == null)");
                    builder.Append(indent).AppendLine("    {");
                    builder.Append(indent)
                        .Append("        converter = converterAttribute.CreateConverter(typeof(")
                        .Append(ToTypeOfTypeName(property.Symbol.Type))
                        .AppendLine("));");
                    builder.Append(indent).AppendLine("    }");
                    builder.Append(indent).AppendLine("    else");
                    builder.Append(indent).AppendLine("    {");
                    builder.Append(indent).AppendLine("        converter = (global::System.Text.Json.Serialization.JsonConverter?)global::System.Activator.CreateInstance(converterAttribute.ConverterType);");
                    builder.Append(indent).AppendLine("    }");
                    builder.AppendLine();
                    builder.Append(indent).AppendLine("    if (converter == null)");
                    builder.Append(indent).AppendLine("    {");
                    builder.Append(indent).AppendLine("        throw new global::System.InvalidOperationException(\"Patch DTO property converter could not be created.\");");
                    builder.Append(indent).AppendLine("    }");
                    builder.AppendLine();
                    builder.Append(indent).AppendLine("    mergePatchOptions.Converters.Insert(0, converter);");
                }

                if (property.JsonNumberHandling.HasValue)
                {
                    builder.Append(indent)
                        .Append("    mergePatchOptions.NumberHandling = (global::System.Text.Json.Serialization.JsonNumberHandling)")
                        .Append(property.JsonNumberHandling.Value)
                        .AppendLine(";");
                }

                builder.Append(indent).AppendLine("    return mergePatchOptions;");
                builder.Append(indent).AppendLine("}");
            }

            builder.AppendLine();
            builder.Append(indent).Append("private static string ").Append(generatedNames.GetJsonNameMethodName).AppendLine("(string clrName, string? explicitJsonName, global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (explicitJsonName != null)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        return explicitJsonName;");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    return options.PropertyNamingPolicy == null ? clrName : options.PropertyNamingPolicy.ConvertName(clrName);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).Append("private static bool ").Append(generatedNames.JsonNameEqualsMethodName).AppendLine("(string actualName, string expectedName, global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    var comparison = options.PropertyNameCaseInsensitive ? global::System.StringComparison.OrdinalIgnoreCase : global::System.StringComparison.Ordinal;");
            builder.Append(indent).AppendLine("    return global::System.String.Equals(actualName, expectedName, comparison);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).Append("private static void ").Append(generatedNames.ValidateJsonNamesMethodName).AppendLine("(global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    var comparer = options.PropertyNameCaseInsensitive ? global::System.StringComparer.OrdinalIgnoreCase : global::System.StringComparer.Ordinal;");
            builder.Append(indent).AppendLine("    var jsonNames = new global::System.Collections.Generic.Dictionary<string, string>(comparer);");

            foreach (var property in model.Properties)
            {
                builder.Append(indent)
                    .Append("    ")
                    .Append(generatedNames.AddJsonNameMethodName)
                    .Append("(jsonNames, ")
                    .Append(generatedNames.GetJsonNameMethodName)
                    .Append("(")
                    .Append(ToLiteral(property.Name))
                    .Append(", ")
                    .Append(property.ExplicitJsonName == null ? "null" : ToLiteral(property.ExplicitJsonName))
                    .Append(", options), ")
                    .Append(ToLiteral(property.Name))
                    .AppendLine(");");
            }

            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent)
                .Append("private static void ")
                .Append(generatedNames.AddJsonNameMethodName)
                .AppendLine("(global::System.Collections.Generic.Dictionary<string, string> jsonNames, string jsonName, string clrName)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (jsonNames.TryGetValue(jsonName, out var existingClrName))");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        throw new global::System.Text.Json.JsonException(\"Merge patch DTO maps CLR properties '\" + existingClrName + \"' and '\" + clrName + \"' to duplicate JSON property name '\" + jsonName + \"'.\");");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    jsonNames.Add(jsonName, clrName);");
            builder.Append(indent).AppendLine("}");
        }

        private static void ReportPropertyAttributeConflicts(PatchDtoModel model, SourceProductionContext context)
        {
            foreach (var property in model.Properties)
            {
                if (property.HasPatchIgnore && property.PatchToTargetName != null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.ConflictingPatchAttributes,
                        property.Location,
                        property.Name,
                        "PatchIgnore and PatchTo"));
                }

                if (property.HasPatchIgnore && property.PatchUsingMethodName != null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.ConflictingPatchAttributes,
                        property.Location,
                        property.Name,
                        "PatchIgnore and PatchUsing"));
                }

                if (property.PatchToTargetName != null && property.PatchUsingMethodName != null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.ConflictingPatchAttributes,
                        property.Location,
                        property.Name,
                        "PatchTo and PatchUsing"));
                }
            }
        }

        private static void ReportTargetlessMappingAttributes(PatchDtoModel model, SourceProductionContext context)
        {
            foreach (var property in model.Properties)
            {
                var mappingAttributes = GetTargetlessMappingAttributeList(property);
                if (mappingAttributes == null)
                {
                    continue;
                }

                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.TargetlessMappingAttributeIgnored,
                    property.Location,
                    property.Name,
                    mappingAttributes));
            }
        }

        private static string? GetTargetlessMappingAttributeList(PatchPropertyModel property)
        {
            var builder = new StringBuilder();

            if (property.HasPatchIgnore)
            {
                builder.Append("PatchIgnore");
            }

            if (property.PatchToTargetName != null)
            {
                AppendAttributeName(builder, "PatchTo");
            }

            if (property.PatchUsingMethodName != null)
            {
                AppendAttributeName(builder, "PatchUsing");
            }

            return builder.Length == 0 ? null : builder.ToString();
        }

        private static void AppendAttributeName(StringBuilder builder, string name)
        {
            if (builder.Length > 0)
            {
                builder.Append(", ");
            }

            builder.Append(name);
        }

        private static bool HasConflictingApplyAttributes(PatchPropertyModel property)
        {
            return (property.HasPatchIgnore && property.PatchToTargetName != null) ||
                   (property.HasPatchIgnore && property.PatchUsingMethodName != null) ||
                   (property.PatchToTargetName != null && property.PatchUsingMethodName != null);
        }

        private static bool IsValidPatchUsingMethod(
            IMethodSymbol method,
            PatchDtoModel model,
            PatchTargetModel target,
            PatchPropertyModel property)
        {
            if (!method.IsStatic || !method.ReturnsVoid || method.IsGenericMethod)
            {
                return false;
            }

            if (method.Parameters.Length == 2)
            {
                return HasOnlyValueParameters(method) &&
                       IsSameType(method.Parameters[0].Type, target.TargetType) &&
                       IsSameType(method.Parameters[1].Type, property.Symbol.Type);
            }

            if (method.Parameters.Length == 3)
            {
                return HasOnlyValueParameters(method) &&
                       IsSameType(method.Parameters[0].Type, model.TypeSymbol) &&
                       IsSameType(method.Parameters[1].Type, target.TargetType) &&
                       IsSameType(method.Parameters[2].Type, property.Symbol.Type);
            }

            return false;
        }

        private static bool HasOnlyValueParameters(IMethodSymbol method)
        {
            return method.Parameters.All(parameter => parameter.RefKind == RefKind.None);
        }

        private static bool IsSameType(ITypeSymbol left, ITypeSymbol right)
        {
            return SymbolEqualityComparer.Default.Equals(left, right);
        }

        private static bool HasAccessibleSetter(
            Compilation compilation,
            INamedTypeSymbol patchType,
            ITypeSymbol targetType,
            IPropertySymbol property)
        {
            var setter = property.SetMethod;
            if (setter == null)
            {
                return false;
            }

            if (setter.IsInitOnly)
            {
                return false;
            }

            return compilation.IsSymbolAccessibleWithin(setter, patchType, targetType);
        }

        private static bool CanAssign(Compilation compilation, ITypeSymbol sourceType, ITypeSymbol targetType)
        {
            var conversion = compilation.ClassifyConversion(sourceType, targetType);
            return conversion.IsImplicit && CanAssignNullability(sourceType, targetType);
        }

        private static bool CanAssignNullability(ITypeSymbol sourceType, ITypeSymbol targetType)
        {
            return CanAssignNullability(
                sourceType,
                sourceType.NullableAnnotation,
                targetType,
                targetType.NullableAnnotation);
        }

        private static bool CanAssignNullability(
            ITypeSymbol sourceType,
            NullableAnnotation sourceAnnotation,
            ITypeSymbol targetType,
            NullableAnnotation targetAnnotation)
        {
            if (CanBeNull(sourceType, sourceAnnotation) && !CanAcceptNull(targetType, targetAnnotation))
            {
                return false;
            }

            if (sourceType is IArrayTypeSymbol sourceArray && targetType is IArrayTypeSymbol targetArray)
            {
                return CanAssignNullability(sourceArray.ElementType, targetArray.ElementType);
            }

            if (targetType is INamedTypeSymbol targetNamed)
            {
                var sourceNamed = FindAssignableSourceTypeArgumentShape(sourceType, targetNamed);
                if (sourceNamed != null && !CanAssignTypeArgumentNullability(sourceNamed, targetNamed))
                {
                    return false;
                }
            }

            return true;
        }

        private static bool CanAssignTypeArgumentNullability(INamedTypeSymbol sourceType, INamedTypeSymbol targetType)
        {
            if (!targetType.IsGenericType)
            {
                return true;
            }

            if (sourceType.TypeArguments.Length != targetType.TypeArguments.Length)
            {
                return true;
            }

            for (var i = 0; i < sourceType.TypeArguments.Length; i++)
            {
                if (!CanAssignNullability(
                    sourceType.TypeArguments[i],
                    GetTypeArgumentNullableAnnotation(sourceType, i),
                    targetType.TypeArguments[i],
                    GetTypeArgumentNullableAnnotation(targetType, i)))
                {
                    return false;
                }
            }

            return true;
        }

        private static INamedTypeSymbol? FindAssignableSourceTypeArgumentShape(ITypeSymbol sourceType, INamedTypeSymbol targetType)
        {
            if (!targetType.IsGenericType)
            {
                return null;
            }

            if (sourceType is INamedTypeSymbol sourceNamed)
            {
                for (var current = sourceNamed; current != null; current = current.BaseType)
                {
                    if (IsSameOriginalDefinition(current, targetType))
                    {
                        return current;
                    }
                }
            }

            foreach (var interfaceType in sourceType.AllInterfaces)
            {
                if (IsSameOriginalDefinition(interfaceType, targetType))
                {
                    return interfaceType;
                }
            }

            return null;
        }

        private static bool CanBeNull(ITypeSymbol type, NullableAnnotation annotation)
        {
            return IsNullableValueType(type) || (!type.IsValueType && annotation == NullableAnnotation.Annotated);
        }

        private static bool CanAcceptNull(ITypeSymbol type, NullableAnnotation annotation)
        {
            if (IsNullableValueType(type))
            {
                return true;
            }

            return !type.IsValueType && annotation != NullableAnnotation.NotAnnotated;
        }

        private static bool IsNullableValueType(ITypeSymbol type)
        {
            return type is INamedTypeSymbol namedType
                && namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
        }

        private static bool IsSameOriginalDefinition(INamedTypeSymbol left, INamedTypeSymbol right)
        {
            return SymbolEqualityComparer.Default.Equals(left.OriginalDefinition, right.OriginalDefinition);
        }

        private static NullableAnnotation GetTypeArgumentNullableAnnotation(INamedTypeSymbol type, int index)
        {
            var annotations = type.TypeArgumentNullableAnnotations;
            if (annotations.IsDefaultOrEmpty || index >= annotations.Length)
            {
                return type.TypeArguments[index].NullableAnnotation;
            }

            return annotations[index];
        }

        private static string ToTypeName(ITypeSymbol symbol)
        {
            return symbol.ToDisplayString(FullyQualifiedNullableFormat);
        }

        private static string ToTypeOfTypeName(ITypeSymbol symbol)
        {
            return symbol.ToDisplayString(FullyQualifiedTypeOfFormat);
        }

        private static string GetGlobalTypeName(string namespaceName, string typeName)
        {
            return string.IsNullOrEmpty(namespaceName)
                ? "global::" + typeName
                : "global::" + namespaceName + "." + typeName;
        }

        private static string GetJsonOptionsExpression(PatchPropertyModel property, string optionsExpression, GeneratedNames generatedNames)
        {
            return property.HasPropertyJsonOptions
                ? generatedNames.GetJsonOptionsMethodName(property) + "(" + optionsExpression + ")"
                : optionsExpression;
        }

        private sealed class GeneratedNames
        {
            private readonly Dictionary<string, string> initOnlySetterMethodNames;
            private readonly Dictionary<string, string> jsonOptionsMethodNames;

            private GeneratedNames(
                string converterTypeName,
                string providedFieldName,
                string wasProvidedMethodName,
                string markProvidedMethodName,
                string clearProvidedMethodName,
                string getJsonNameMethodName,
                string jsonNameEqualsMethodName,
                string validateJsonNamesMethodName,
                string addJsonNameMethodName,
                Dictionary<string, string> initOnlySetterMethodNames,
                Dictionary<string, string> jsonOptionsMethodNames)
            {
                ConverterTypeName = converterTypeName;
                ProvidedFieldName = providedFieldName;
                WasProvidedMethodName = wasProvidedMethodName;
                MarkProvidedMethodName = markProvidedMethodName;
                ClearProvidedMethodName = clearProvidedMethodName;
                GetJsonNameMethodName = getJsonNameMethodName;
                JsonNameEqualsMethodName = jsonNameEqualsMethodName;
                ValidateJsonNamesMethodName = validateJsonNamesMethodName;
                AddJsonNameMethodName = addJsonNameMethodName;
                this.initOnlySetterMethodNames = initOnlySetterMethodNames;
                this.jsonOptionsMethodNames = jsonOptionsMethodNames;
            }

            public string ConverterTypeName { get; }

            public string ProvidedFieldName { get; }

            public string WasProvidedMethodName { get; }

            public string MarkProvidedMethodName { get; }

            public string ClearProvidedMethodName { get; }

            public string GetJsonNameMethodName { get; }

            public string JsonNameEqualsMethodName { get; }

            public string ValidateJsonNamesMethodName { get; }

            public string AddJsonNameMethodName { get; }

            public static GeneratedNames Create(PatchDtoModel model)
            {
                var memberNames = new HashSet<string>(StringComparer.Ordinal);
                foreach (var member in model.TypeSymbol.GetMembers())
                {
                    memberNames.Add(member.Name);
                }

                memberNames.Add("Has");
                memberNames.Add("ApplyTo");
                memberNames.Add("ProvidedFields");

                var namespaceTypeNames = new HashSet<string>(StringComparer.Ordinal);
                foreach (var type in model.TypeSymbol.ContainingNamespace.GetTypeMembers())
                {
                    namespaceTypeNames.Add(type.Name);
                }

                var converterTypeName = GetAvailableName("__MergePatchDto" + model.Name + "JsonConverter", namespaceTypeNames);
                var providedFieldName = GetAvailableName("__mergePatchDtoProvided", memberNames);
                var wasProvidedMethodName = GetAvailableName("__MergePatchDtoWasProvided", memberNames);
                var markProvidedMethodName = GetAvailableName("__MergePatchDtoMarkProvided", memberNames);
                var clearProvidedMethodName = GetAvailableName("__MergePatchDtoClearProvided", memberNames);

                var converterMemberNames = new HashSet<string>(StringComparer.Ordinal);
                var initOnlySetterMethodNames = new Dictionary<string, string>(StringComparer.Ordinal);
                foreach (var property in model.Properties.Where(property => property.IsInitOnly))
                {
                    initOnlySetterMethodNames.Add(
                        property.Name,
                        GetAvailableName("__MergePatchDtoSet" + property.Name, converterMemberNames));
                }

                var jsonOptionsMethodNames = new Dictionary<string, string>(StringComparer.Ordinal);
                foreach (var property in model.Properties.Where(property => property.HasPropertyJsonOptions))
                {
                    jsonOptionsMethodNames.Add(
                        property.Name,
                        GetAvailableName("__MergePatchDtoGet" + property.Name + "JsonOptions", converterMemberNames));
                }

                var getJsonNameMethodName = GetAvailableName("__MergePatchDtoGetJsonName", converterMemberNames);
                var jsonNameEqualsMethodName = GetAvailableName("__MergePatchDtoJsonNameEquals", converterMemberNames);
                var validateJsonNamesMethodName = GetAvailableName("__MergePatchDtoValidateJsonNames", converterMemberNames);
                var addJsonNameMethodName = GetAvailableName("__MergePatchDtoAddJsonName", converterMemberNames);

                return new GeneratedNames(
                    converterTypeName,
                    providedFieldName,
                    wasProvidedMethodName,
                    markProvidedMethodName,
                    clearProvidedMethodName,
                    getJsonNameMethodName,
                    jsonNameEqualsMethodName,
                    validateJsonNamesMethodName,
                    addJsonNameMethodName,
                    initOnlySetterMethodNames,
                    jsonOptionsMethodNames);
            }

            public string GetInitOnlySetterMethodName(PatchPropertyModel property)
            {
                return initOnlySetterMethodNames[property.Name];
            }

            public string GetJsonOptionsMethodName(PatchPropertyModel property)
            {
                return jsonOptionsMethodNames[property.Name];
            }

            private static string GetAvailableName(string baseName, HashSet<string> usedNames)
            {
                if (usedNames.Add(baseName))
                {
                    return baseName;
                }

                var suffix = 1;
                while (true)
                {
                    var candidate = baseName + "_" + suffix;
                    if (usedNames.Add(candidate))
                    {
                        return candidate;
                    }

                    suffix++;
                }
            }
        }

        private static string EscapeIdentifier(string identifier)
        {
            if (SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ||
                SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None)
            {
                return "@" + identifier;
            }

            return identifier;
        }

        private static string ToLiteral(string value)
        {
            var builder = new StringBuilder(value.Length + 2);
            builder.Append('"');
            foreach (var c in value)
            {
                switch (c)
                {
                    case '\\':
                        builder.Append(@"\\");
                        break;
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\0':
                        builder.Append(@"\0");
                        break;
                    case '\a':
                        builder.Append(@"\a");
                        break;
                    case '\b':
                        builder.Append(@"\b");
                        break;
                    case '\f':
                        builder.Append(@"\f");
                        break;
                    case '\n':
                        builder.Append(@"\n");
                        break;
                    case '\r':
                        builder.Append(@"\r");
                        break;
                    case '\t':
                        builder.Append(@"\t");
                        break;
                    case '\v':
                        builder.Append(@"\v");
                        break;
                    default:
                        if (char.IsControl(c))
                        {
                            builder.Append("\\u").Append(((int)c).ToString("x4"));
                        }
                        else
                        {
                            builder.Append(c);
                        }

                        break;
                }
            }

            builder.Append('"');
            return builder.ToString();
        }
    }
}
