using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MergePatchDto.Generators
{
    internal static class SourceTextEmitter
    {
        private static readonly SymbolDisplayFormat FullyQualifiedNullableFormat = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

        public static string Emit(PatchDtoModel model, Compilation compilation, SourceProductionContext context)
        {
            if (model.Targets.Length > 0)
            {
                ReportPropertyAttributeConflicts(model, context);
            }
            else
            {
                ReportTargetlessMappingAttributes(model, context);
            }

            var builder = new StringBuilder();
            var converterName = model.Name + "JsonConverter";
            var converterTypeName = GetGlobalTypeName(model.NamespaceName, converterName);
            var indent = string.IsNullOrEmpty(model.NamespaceName) ? string.Empty : "    ";

            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            if (!string.IsNullOrEmpty(model.NamespaceName))
            {
                builder.Append("namespace ").Append(model.NamespaceName).AppendLine();
                builder.AppendLine("{");
            }

            builder.Append(indent)
                .Append("[global::System.Text.Json.Serialization.JsonConverter(typeof(")
                .Append(converterTypeName)
                .AppendLine("))]");
            builder.Append(indent)
                .Append(model.Accessibility)
                .Append(" partial class ")
                .Append(model.Name)
                .AppendLine();
            builder.Append(indent).AppendLine("{");

            AppendPresenceApi(builder, model, indent + "    ");

            foreach (var target in model.Targets)
            {
                AppendApplyTo(builder, model, target, compilation, context, indent + "    ");
            }

            builder.Append(indent).AppendLine("}");
            builder.AppendLine();

            AppendConverter(builder, model, converterName, indent);

            if (!string.IsNullOrEmpty(model.NamespaceName))
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        public static string GetHintName(PatchDtoModel model)
        {
            var name = model.TypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var builder = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    builder.Append(c);
                }
                else
                {
                    builder.Append('_');
                }
            }

            return builder + ".MergePatch.g.cs";
        }

        private static void AppendPresenceApi(StringBuilder builder, PatchDtoModel model, string indent)
        {
            builder.Append(indent).AppendLine("private readonly global::System.Collections.Generic.HashSet<string> _provided = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);");
            builder.AppendLine();
            builder.Append(indent).AppendLine("public ProvidedFields Has");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    get { return new ProvidedFields(this); }");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).AppendLine("public bool WasProvided(string propertyName)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (propertyName == null)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        throw new global::System.ArgumentNullException(nameof(propertyName));");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    return _provided.Contains(propertyName);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).AppendLine("internal void __MergePatchMarkProvided(string propertyName)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    _provided.Add(propertyName);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).AppendLine("internal void __MergePatchClearProvided()");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    _provided.Clear();");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).AppendLine("public readonly struct ProvidedFields");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).Append("    private readonly ").Append(model.TypeName).AppendLine(" _patch;");
            builder.AppendLine();
            builder.Append(indent).Append("    public ProvidedFields(").Append(model.TypeName).AppendLine(" patch)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        _patch = patch;");
            builder.Append(indent).AppendLine("    }");

            foreach (var property in model.Properties)
            {
                builder.AppendLine();
                builder.Append(indent)
                    .Append("    public bool ")
                    .Append(EscapeIdentifier(property.Name))
                    .Append(" { get { return _patch.WasProvided(")
                    .Append(ToLiteral(property.Name))
                    .AppendLine("); } }");
            }

            builder.Append(indent).AppendLine("}");
        }

        private static void AppendApplyTo(
            StringBuilder builder,
            PatchDtoModel model,
            PatchTargetModel target,
            Compilation compilation,
            SourceProductionContext context,
            string indent)
        {
            var targetTypeName = ToTypeName(target.TargetType);

            builder.AppendLine();
            builder.Append(indent).Append("public void ApplyTo(").Append(targetTypeName).AppendLine(" target)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (target == null)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        throw new global::System.ArgumentNullException(nameof(target));");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    var has = Has;");

            foreach (var property in model.Properties)
            {
                if (HasConflictingApplyAttributes(property))
                {
                    continue;
                }

                if (property.HasPatchIgnore)
                {
                    continue;
                }

                if (property.PatchUsingMethodName != null)
                {
                    AppendPatchUsing(builder, model, target, property, context, indent + "    ");
                    continue;
                }

                AppendDirectAssignment(builder, model, target, property, compilation, context, indent + "    ");
            }

            builder.Append(indent).AppendLine("}");
        }

        private static void AppendDirectAssignment(
            StringBuilder builder,
            PatchDtoModel model,
            PatchTargetModel target,
            PatchPropertyModel property,
            Compilation compilation,
            SourceProductionContext context,
            string indent)
        {
            var targetPropertyName = property.PatchToTargetName ?? property.Name;
            var targetProperty = target.TargetType
                .GetMembers(targetPropertyName)
                .OfType<IPropertySymbol>()
                .FirstOrDefault(member => !member.IsStatic);

            if (targetProperty == null)
            {
                var descriptor = property.PatchToTargetName == null
                    ? Diagnostics.ConventionTargetMissing
                    : Diagnostics.PatchToTargetMissing;

                if (property.PatchToTargetName == null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        descriptor,
                        property.Location,
                        property.Name,
                        ToTypeName(target.TargetType)));
                }
                else
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        descriptor,
                        property.Location,
                        property.Name,
                        targetPropertyName,
                        ToTypeName(target.TargetType)));
                }

                return;
            }

            if (!HasAccessibleSetter(compilation, model.TypeSymbol, target.TargetType, targetProperty))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.TargetPropertyNoSetter,
                    property.Location,
                    targetPropertyName,
                    ToTypeName(target.TargetType),
                    property.Name));
                return;
            }

            if (!CanAssign(compilation, property.Symbol.Type, targetProperty.Type))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.PatchPropertyCannotAssignToTargetProperty,
                    property.Location,
                    property.Name,
                    ToTypeName(property.Symbol.Type),
                    targetPropertyName,
                    ToTypeName(targetProperty.Type),
                    ToTypeName(target.TargetType)));
                return;
            }

            builder.AppendLine();
            builder.Append(indent).Append("if (has.").Append(EscapeIdentifier(property.Name)).AppendLine(")");
            builder.Append(indent)
                .Append("    target.")
                .Append(EscapeIdentifier(targetPropertyName))
                .Append(" = ")
                .Append(EscapeIdentifier(property.Name))
                .AppendLine(";");
        }

        private static void AppendPatchUsing(
            StringBuilder builder,
            PatchDtoModel model,
            PatchTargetModel target,
            PatchPropertyModel property,
            SourceProductionContext context,
            string indent)
        {
            var methodName = property.PatchUsingMethodName!;
            var methods = model.TypeSymbol
                .GetMembers(methodName)
                .OfType<IMethodSymbol>()
                .Where(method => method.MethodKind == MethodKind.Ordinary)
                .ToArray();

            if (methods.Length == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.PatchUsingMethodMissing,
                    property.Location,
                    methodName,
                    property.Name));
                return;
            }

            var method = methods.FirstOrDefault(candidate => IsValidPatchUsingMethod(candidate, model, target, property));
            if (method == null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.PatchUsingMethodInvalid,
                    property.Location,
                    methodName,
                    property.Name,
                    ToTypeName(target.TargetType),
                    property.TypeName,
                    model.TypeName));
                return;
            }

            builder.AppendLine();
            builder.Append(indent).Append("if (has.").Append(EscapeIdentifier(property.Name)).AppendLine(")");
            builder.Append(indent).Append("    ").Append(EscapeIdentifier(methodName)).Append("(");
            if (method.Parameters.Length == 3)
            {
                builder.Append("this, ");
            }

            builder.Append("target, ").Append(EscapeIdentifier(property.Name)).AppendLine(");");
        }

        private static void AppendConverter(StringBuilder builder, PatchDtoModel model, string converterName, string indent)
        {
            builder.Append(indent)
                .Append(model.Accessibility)
                .Append(" sealed class ")
                .Append(converterName)
                .Append(" : global::System.Text.Json.Serialization.JsonConverter<")
                .Append(model.TypeName)
                .AppendLine(">");
            builder.Append(indent).AppendLine("{");

            AppendConverterRead(builder, model, indent + "    ");
            builder.AppendLine();
            AppendConverterWrite(builder, model, indent + "    ");
            AppendConverterHelpers(builder, model, indent + "    ");

            builder.Append(indent).AppendLine("}");
        }

        private static void AppendConverterRead(StringBuilder builder, PatchDtoModel model, string indent)
        {
            builder.Append(indent)
                .Append("public override ")
                .Append(model.TypeName)
                .AppendLine("? Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        return null;");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    if (reader.TokenType != global::System.Text.Json.JsonTokenType.StartObject)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        throw new global::System.Text.Json.JsonException(\"Patch DTO JSON payload must be an object.\");");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    using (var document = global::System.Text.Json.JsonDocument.ParseValue(ref reader))");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).Append("        var patch = new ").Append(model.TypeName).AppendLine("();");
            builder.AppendLine();
            builder.Append(indent).AppendLine("        foreach (var jsonProperty in document.RootElement.EnumerateObject())");
            builder.Append(indent).AppendLine("        {");
            builder.Append(indent).AppendLine("            var jsonPropertyName = jsonProperty.Name;");

            foreach (var property in model.Properties)
            {
                builder.AppendLine();
                builder.Append(indent).Append("            if (__MergePatchJsonNameEquals(jsonPropertyName, __MergePatchGetJsonName(")
                    .Append(ToLiteral(property.Name))
                    .Append(", ")
                    .Append(property.ExplicitJsonName == null ? "null" : ToLiteral(property.ExplicitJsonName))
                    .AppendLine(", options), options))");
                builder.Append(indent).AppendLine("            {");

                var deserializeExpression = "global::System.Text.Json.JsonSerializer.Deserialize<" + property.TypeName + ">(jsonProperty.Value, options)";
                if (property.IsInitOnly)
                {
                    builder.Append(indent)
                        .Append("                __MergePatchSet")
                        .Append(property.Name)
                        .Append("(patch, ")
                        .Append(deserializeExpression)
                        .AppendLine(");");
                }
                else
                {
                    builder.Append(indent)
                        .Append("                patch.")
                        .Append(EscapeIdentifier(property.Name))
                        .Append(" = ")
                        .Append(deserializeExpression)
                        .AppendLine(";");
                }

                builder.Append(indent)
                    .Append("                patch.__MergePatchMarkProvided(")
                    .Append(ToLiteral(property.Name))
                    .AppendLine(");");
                builder.Append(indent).AppendLine("                continue;");
                builder.Append(indent).AppendLine("            }");
            }

            if (model.RejectUnknownProperties)
            {
                builder.AppendLine();
                builder.Append(indent).AppendLine("            throw new global::System.Text.Json.JsonException(\"Unknown JSON property '\" + jsonPropertyName + \"'.\");");
            }

            builder.Append(indent).AppendLine("        }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("        return patch;");
            builder.Append(indent).AppendLine("    }");
            builder.Append(indent).AppendLine("}");
        }

        private static void AppendConverterWrite(StringBuilder builder, PatchDtoModel model, string indent)
        {
            builder.Append(indent)
                .Append("public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ")
                .Append(model.TypeName)
                .AppendLine(" value, global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    writer.WriteStartObject();");

            foreach (var property in model.Properties)
            {
                builder.AppendLine();
                builder.Append(indent)
                    .Append("    if (value.WasProvided(")
                    .Append(ToLiteral(property.Name))
                    .AppendLine("))");
                builder.Append(indent).AppendLine("    {");
                builder.Append(indent)
                    .Append("        writer.WritePropertyName(__MergePatchGetJsonName(")
                    .Append(ToLiteral(property.Name))
                    .Append(", ")
                    .Append(property.ExplicitJsonName == null ? "null" : ToLiteral(property.ExplicitJsonName))
                    .AppendLine(", options));");
                builder.Append(indent)
                    .Append("        global::System.Text.Json.JsonSerializer.Serialize<")
                    .Append(property.TypeName)
                    .Append(">(writer, value.")
                    .Append(EscapeIdentifier(property.Name))
                    .AppendLine(", options);");
                builder.Append(indent).AppendLine("    }");
            }

            builder.AppendLine();
            builder.Append(indent).AppendLine("    writer.WriteEndObject();");
            builder.Append(indent).AppendLine("}");
        }

        private static void AppendConverterHelpers(StringBuilder builder, PatchDtoModel model, string indent)
        {
            foreach (var property in model.Properties.Where(property => property.IsInitOnly))
            {
                builder.AppendLine();
                builder.Append(indent)
                    .Append("private static void __MergePatchSet")
                    .Append(property.Name)
                    .Append("(")
                    .Append(model.TypeName)
                    .Append(" patch, ")
                    .Append(property.TypeName)
                    .AppendLine(" value)");
                builder.Append(indent).AppendLine("{");
                builder.Append(indent)
                    .Append("    var property = typeof(")
                    .Append(model.TypeName)
                    .Append(").GetProperty(")
                    .Append(ToLiteral(property.Name))
                    .AppendLine(", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public);");
                builder.Append(indent).AppendLine("    if (property == null)");
                builder.Append(indent).AppendLine("    {");
                builder.Append(indent).AppendLine("        throw new global::System.InvalidOperationException(\"Patch DTO property could not be found.\");");
                builder.Append(indent).AppendLine("    }");
                builder.AppendLine();
                builder.Append(indent).AppendLine("    property.SetValue(patch, value, null);");
                builder.Append(indent).AppendLine("}");
            }

            builder.AppendLine();
            builder.Append(indent).AppendLine("private static string __MergePatchGetJsonName(string clrName, string? explicitJsonName, global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    if (explicitJsonName != null)");
            builder.Append(indent).AppendLine("    {");
            builder.Append(indent).AppendLine("        return explicitJsonName;");
            builder.Append(indent).AppendLine("    }");
            builder.AppendLine();
            builder.Append(indent).AppendLine("    return options.PropertyNamingPolicy == null ? clrName : options.PropertyNamingPolicy.ConvertName(clrName);");
            builder.Append(indent).AppendLine("}");
            builder.AppendLine();
            builder.Append(indent).AppendLine("private static bool __MergePatchJsonNameEquals(string actualName, string expectedName, global::System.Text.Json.JsonSerializerOptions options)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    var comparison = options.PropertyNameCaseInsensitive ? global::System.StringComparison.OrdinalIgnoreCase : global::System.StringComparison.Ordinal;");
            builder.Append(indent).AppendLine("    return global::System.String.Equals(actualName, expectedName, comparison);");
            builder.Append(indent).AppendLine("}");
        }

        private static void ReportPropertyAttributeConflicts(PatchDtoModel model, SourceProductionContext context)
        {
            foreach (var property in model.Properties)
            {
                if (property.HasPatchIgnore && property.PatchToTargetName != null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.ConflictingPatchAttributes,
                        property.Location,
                        property.Name,
                        "PatchIgnore and PatchTo"));
                }

                if (property.HasPatchIgnore && property.PatchUsingMethodName != null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.ConflictingPatchAttributes,
                        property.Location,
                        property.Name,
                        "PatchIgnore and PatchUsing"));
                }

                if (property.PatchToTargetName != null && property.PatchUsingMethodName != null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.ConflictingPatchAttributes,
                        property.Location,
                        property.Name,
                        "PatchTo and PatchUsing"));
                }
            }
        }

        private static void ReportTargetlessMappingAttributes(PatchDtoModel model, SourceProductionContext context)
        {
            foreach (var property in model.Properties)
            {
                var mappingAttributes = GetTargetlessMappingAttributeList(property);
                if (mappingAttributes == null)
                {
                    continue;
                }

                context.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.TargetlessMappingAttributeIgnored,
                    property.Location,
                    property.Name,
                    mappingAttributes));
            }
        }

        private static string? GetTargetlessMappingAttributeList(PatchPropertyModel property)
        {
            var builder = new StringBuilder();

            if (property.HasPatchIgnore)
            {
                builder.Append("PatchIgnore");
            }

            if (property.PatchToTargetName != null)
            {
                AppendAttributeName(builder, "PatchTo");
            }

            if (property.PatchUsingMethodName != null)
            {
                AppendAttributeName(builder, "PatchUsing");
            }

            return builder.Length == 0 ? null : builder.ToString();
        }

        private static void AppendAttributeName(StringBuilder builder, string name)
        {
            if (builder.Length > 0)
            {
                builder.Append(", ");
            }

            builder.Append(name);
        }

        private static bool HasConflictingApplyAttributes(PatchPropertyModel property)
        {
            return (property.HasPatchIgnore && property.PatchToTargetName != null) ||
                   (property.HasPatchIgnore && property.PatchUsingMethodName != null) ||
                   (property.PatchToTargetName != null && property.PatchUsingMethodName != null);
        }

        private static bool IsValidPatchUsingMethod(
            IMethodSymbol method,
            PatchDtoModel model,
            PatchTargetModel target,
            PatchPropertyModel property)
        {
            if (!method.IsStatic || !method.ReturnsVoid || method.IsGenericMethod)
            {
                return false;
            }

            if (method.Parameters.Length == 2)
            {
                return HasOnlyValueParameters(method) &&
                       IsSameType(method.Parameters[0].Type, target.TargetType) &&
                       IsSameType(method.Parameters[1].Type, property.Symbol.Type);
            }

            if (method.Parameters.Length == 3)
            {
                return HasOnlyValueParameters(method) &&
                       IsSameType(method.Parameters[0].Type, model.TypeSymbol) &&
                       IsSameType(method.Parameters[1].Type, target.TargetType) &&
                       IsSameType(method.Parameters[2].Type, property.Symbol.Type);
            }

            return false;
        }

        private static bool HasOnlyValueParameters(IMethodSymbol method)
        {
            return method.Parameters.All(parameter => parameter.RefKind == RefKind.None);
        }

        private static bool IsSameType(ITypeSymbol left, ITypeSymbol right)
        {
            return SymbolEqualityComparer.Default.Equals(left, right);
        }

        private static bool HasAccessibleSetter(
            Compilation compilation,
            INamedTypeSymbol patchType,
            ITypeSymbol targetType,
            IPropertySymbol property)
        {
            var setter = property.SetMethod;
            if (setter == null)
            {
                return false;
            }

            if (setter.IsInitOnly)
            {
                return false;
            }

            return compilation.IsSymbolAccessibleWithin(setter, patchType, targetType);
        }

        private static bool CanAssign(Compilation compilation, ITypeSymbol sourceType, ITypeSymbol targetType)
        {
            var conversion = compilation.ClassifyConversion(sourceType, targetType);
            return conversion.IsImplicit;
        }

        private static string ToTypeName(ITypeSymbol symbol)
        {
            return symbol.ToDisplayString(FullyQualifiedNullableFormat);
        }

        private static string GetGlobalTypeName(string namespaceName, string typeName)
        {
            return string.IsNullOrEmpty(namespaceName)
                ? "global::" + typeName
                : "global::" + namespaceName + "." + typeName;
        }

        private static string EscapeIdentifier(string identifier)
        {
            if (SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ||
                SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None)
            {
                return "@" + identifier;
            }

            return identifier;
        }

        private static string ToLiteral(string value)
        {
            var builder = new StringBuilder(value.Length + 2);
            builder.Append('"');
            foreach (var c in value)
            {
                switch (c)
                {
                    case '\\':
                        builder.Append(@"\\");
                        break;
                    case '"':
                        builder.Append("\\\"");
                        break;
                    case '\0':
                        builder.Append(@"\0");
                        break;
                    case '\a':
                        builder.Append(@"\a");
                        break;
                    case '\b':
                        builder.Append(@"\b");
                        break;
                    case '\f':
                        builder.Append(@"\f");
                        break;
                    case '\n':
                        builder.Append(@"\n");
                        break;
                    case '\r':
                        builder.Append(@"\r");
                        break;
                    case '\t':
                        builder.Append(@"\t");
                        break;
                    case '\v':
                        builder.Append(@"\v");
                        break;
                    default:
                        if (char.IsControl(c))
                        {
                            builder.Append("\\u").Append(((int)c).ToString("x4"));
                        }
                        else
                        {
                            builder.Append(c);
                        }

                        break;
                }
            }

            builder.Append('"');
            return builder.ToString();
        }
    }
}
